version: '3.8'

services:
  database:
    image: mysql:latest
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jk
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: C:\Users\ETEC\Desktop\repositorios kristich\etec-pi-2024-backend-JuanIgnacioKristich
      dockerfile: Dockerfile
    restart: always
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - DATABASE_NAME=jk
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=database
      - PORT=5000  # Cambiar a "database" que es el nombre del servicio MySQL
    user: root

  frontend:
    build:
      context: C:\Users\ETEC\Desktop\repositorios kristich\etec-pi-2024-frontend-JuanIgnacioKristich
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - PORT=3000
      - REACT_APP_BACKEND_URL=backend:5000

  nginx:
    build: C:\Users\ETEC\Desktop\Kristich\basic_deploy_frontend_and_backend/nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend
    restart: always
    networks:
      - app_network

networks:
  app_network:

